EQ_NAME = {

"ENG_gladiator_airframe": "Ilyushin DB-3",
"SOV_i_153_airframe": "Polikarpov I-153",
"SOV_i_15_airframe": "Polikarpov I-15",
"SOV_il_2_airframe": "Ilyushin Il-2",
"SOV_il_4_airframe": "Ilyushin Il-4",
"SOV_i_16_type_10_airframe": "Polikarpov I-16 Type 10",
"SOV_i_16_type_24_airframe": "Polikarpov I-16 Type 24",
"SOV_i_16_type_5_airframe": "Polikarpov I-16 Type 5",
"SOV_mbr_2_airframe": "MBR-2",
"SOV_po_2_airframe": "Polikarpov Po-2",
"SOV_r_10_airframe": "R-10",
"SOV_r_5sh_airframe": "R-5Sh",
"SOV_sb_2m100_airframe": "SB-2M-100",
"SOV_tb_3_airframe": "Tupolev TB-3",
"sov_aa_1": "Anti-Air",
"sov_aa_2": "Anti-Air",
"sov_aa_3": "Anti-Air",
"sov_aa_4": "Anti-Air",
"sov_armoured_car_equipment_1": "Armoured Car",
"sov_art_1": "Artillery",
"sov_art_2": "Artillery",
"sov_art_3": "Artillery",
"sov_art_4": "Artillery",
"sov_at_1": "Anti-Tank",
"sov_at_2": "Anti-Tank",
"sov_at_3": "Anti-Tank",
"sov_at_4": "Anti-Tank",
"sov_fighter_multirole_equipment_1": "Fighter Multirole",
"sov_hv_aa_1": "Heavy Anti-Air",
"sov_hv_aa_2": "Heavy Anti-Air",
"sov_hv_aa_3": "Heavy Anti-Air",
"sov_hv_aa_4": "Heavy Anti-Air",
"sov_hv_art_1": "Heavy Artillery",
"sov_hv_art_2": "Heavy Artillery",
"sov_hv_art_3": "Heavy Artillery",
"sov_hv_art_4": "Heavy Artillery",
"sov_hv_at_1": "Heavy Anti-Tank",
"sov_hv_at_2": "Heavy Anti-Tank",
"sov_inf_1": "Mosin-Nagant",
"sov_inf_2": "AVS-36 + PPD-34",
"sov_inf_3": "SVT-38 + PPD-38",
"sov_hv_inf_1":"Maxim MG + DP-27",
"sov_hv_inf_2":"PTRD-41 + DP-28",
"sov_hv_inf_3":"PTRS-41 + DShK",
"sov_light_equipment_1": "SU-5",
"sov_medium_equipment_0": "T-28",
"sov_medium_equipment_1": "BT-5",
"sov_motorized_equipment_1": "ZiS-5",
"sov_nav_bomber_equipment_1": "Ilyushin Il-4",
"sov_p_art_1": "Packed Artillery",
"sov_p_art_2": "Packed Artillery",
"sov_p_art_3": "Packed Artillery",
"sov_p_art_4": "Packed Artillery",
"sov_scout_car_equipment_1": "Scout Car",
"sov_scout_plane_equipment_1": "R-5",
"sov_strat_bomber_equipment_1": "Tupolev TB-3",
"sov_tac_bomber_equipment_1": "Ilyushin DB-3",
"support_equipment_1": "Support Equipment",
"tank_sov_heavy_chassis_1": "T-35",
"tank_sov_light_chassis_1": "BT-5",
"tank_sov_light_chassis_1_2": "BT-7",
"tank_sov_light_chassis_1_3": "BT-7M",
"tank_sov_medium_chassis_1": "T-28",
"tank_sov_light_chassis_support_1": "T-26",
"tank_sov_medium_chassis_infantry_support_1": "T-28 Infantry Support",
"train_equipment_1": "Trains",
"train_equipment_2": "Trains",
"train_equipment_3": "Trains",
"train_equipment_4": "Trains",
"tank_sov_combat_car_chassis_1": "Armoured Car",
"infantry_equipment_1" : "Light Guns",
"infantry_equipment_2" : "Light Guns",
"sov_inf_4": "Light Guns",
"sov_inf_5": "Light Guns",
"tank_sov_medium_chassis_3": "T-34 (40)",
"tank_sov_medium_chassis_3_2": "T-34 (41)",
"tank_sov_medium_chassis_3_3": "T-34 (42)",
"tank_sov_medium_chassis_3_4": "T-34 (43)",
"tank_sov_medium_chassis_4": "T-34 (44)",
"SOV_yak_1_airframe": "Yakovlev Yak-1",
"SOV_yak_7_airframe": "Yakovlev Yak-7",
"SOV_yak_9d_airframe": "Yakovlev Yak-9D",
"SOV_yak_9u_airframe": "Yakovlev Yak-9U",
"SOV_yak_9ut_airframe": "Yakovlev Yak-9UT",
"SOV_yak_9p_airframe": "Yakovlev Yak-9P",
"SOV_lagg_3_airframe": "Lavochkin LaGG-3",
"SOV_la_5_airframe": "Lavochkin La-5",
"SOV_la_5fn_airframe": "Lavochkin La-5FN",
"SOV_la_7_airframe": "Lavochkin La-7",
"SOV_la_9_airframe": "Lavochkin La-9",
}

EQ_TYPE = {
"SOV_db_3b_airframe": "Tactical Bomber",
"SOV_i_153_airframe": "Fighter",
"SOV_i_15_airframe": "Fighter",
"SOV_il_2_airframe": "Close Air Support",
"SOV_il_4_airframe": "Heavy Bomber",
"SOV_i_16_type_10_airframe": "Multirole",
"SOV_i_16_type_24_airframe": "Multirole",
"SOV_i_16_type_5_airframe": "Multirole",
"SOV_mbr_2_airframe": "Naval Bomber",
"SOV_po_2_airframe": "Close Air Support",
"SOV_r_10_airframe": "Scout Plane",
"SOV_r_5sh_airframe": "Close Air Support",
"SOV_sb_2m100_airframe": "Strike Bomber",
"SOV_tb_3_airframe": "Strategic Bomber",
"sov_aa_1": "Anti-Air",
"sov_aa_2": "Anti-Air",
"sov_aa_3": "Anti-Air",
"sov_aa_4": "Anti-Air",
"SOV_armoured_car_equipment_1": "Armoured Car",
"sov_art_1": "Artillery",
"sov_art_2": "Artillery",
"sov_art_3": "Artillery",
"sov_art_4": "Artillery",
"sov_at_1": "Anti-Tank",
"sov_at_2": "Anti-Tank",
"sov_at_3": "Anti-Tank",
"sov_at_4": "Anti-Tank",
"sov_fighter_multirole_equipment_1": "Fighter Multirole",
"sov_hv_aa_1": "Heavy Anti-Air",
"sov_hv_aa_2": "Heavy Anti-Air",
"sov_hv_aa_3": "Heavy Anti-Air",
"sov_hv_aa_4": "Heavy Anti-Air",
"sov_hv_art_1": "Heavy Artillery",
"sov_hv_art_2": "Heavy Artillery",
"sov_hv_art_3": "Heavy Artillery",
"sov_hv_art_4": "Heavy Artillery",
"sov_hv_at_1": "Heavy Anti-Tank",
"sov_hv_at_2": "Heavy Anti-Tank",
"sov_inf_1": "Light Guns",
"sov_inf_2": "Light Guns",
"sov_inf_3": "Light Guns",
"sov_hv_inf_1":"Heavy Guns",
"sov_hv_inf_2":"Heavy Guns",
"sov_hv_inf_3":"Heavy Guns",
"sov_light_spg_equipment_1": "Light Self-Propelled Gun",
"sov_medium_spg_equipment_1": "Medium Self-Propelled Gun",
"sov_motorized_equipment_1": "Trucks",
"sov_nav_bomber_equipment_1": "Naval Bomber",
"sov_p_art_1": "Packed Artillery",
"sov_p_art_2": "Packed Artillery",
"sov_p_art_3": "Packed Artillery",
"sov_p_art_4": "Packed Artillery",
"sov_scout_car_equipment_1": "Scout Car",
"sov_scout_plane_equipment_1": "Scout Plane",
"sov_strat_bomber_equipment_1": "Strategic Bomber",
"sov_tac_bomber_equipment_1": "Tactical Bomber",
"support_equipment_1": "Support Equipment",
"tank_sov_heavy_chassis_1": "Heavy Tank Chassis",
"tank_sov_light_chassis_1": "Light Tank Chassis",
"tank_sov_light_chassis_1_2": "Light Tank Chassis",
"tank_sov_light_chassis_1_3": "Light Tank Chassis",
"tank_sov_medium_chassis_1": "Medium Tank Chassis",
"tank_sov_light_chassis_support_1": "Light Support Tank",
"tank_sov_medium_chassis_infantry_support_1": "Medium Infantry Support Tank",
"train_equipment_1": "Trains",
"train_equipment_2": "Trains",
"train_equipment_3": "Trains",
"train_equipment_4": "Trains",
"tank_sov_combat_car_chassis_1": "Combat Car",
"infantry_equipment_1": "Light Guns",
"infantry_equipment_2": "Light Guns",
"sov_inf_4": "Light Guns",
"sov_inf_5": "Light Guns",
"tank_sov_medium_chassis_3": "Medium Tank",
"tank_sov_medium_chassis_3_2": "Medium Tank",
"tank_sov_medium_chassis_3_3": "Medium Tank",
"tank_sov_medium_chassis_3_4": "Medium Tank",
"tank_sov_medium_chassis_4": "Medium Tank",
"SOV_yak_1_airframe": "Fighter",
"SOV_yak_7_airframe": "Fighter",
"SOV_yak_9d_airframe": "Fighter",
"SOV_yak_9u_airframe": "Fighter",
"SOV_yak_9ut_airframe": "Fighter",
"SOV_yak_9p_airframe": "Fighter",
"SOV_lagg_3_airframe": "Fighter",
"SOV_la_5_airframe": "Fighter",
"SOV_la_5fn_airframe": "Fighter",
"SOV_la_7_airframe": "Fighter",
"SOV_la_9_airframe": "Fighter",
"sov_hv_inf_4": "Heavy Guns",
"sov_hv_inf_5": "Heavy Guns",
}